feat: syncfolder example
sasjs/minimal-seed-app pull request #18
Opened 2022-06-16 19:44 UTC by allanbowe

2022-06-16 21:07 UTC, allanbowe commented on sasjs/sasjsconfig.json
> +  "syncFolder": "mocks",
aah yes, agreed, will update!

2022-06-21 11:40 UTC, YuryShkoda requested changes

2022-06-21 11:40 UTC, YuryShkoda commented on sasjs/mocks/services/common/appinit.js
> +// this file will return a response
please add blank line

2022-06-21 11:40 UTC, YuryShkoda commented on sasjs/mocks/services/common/getdata.js
> +// this file will take input and return a response
please add blank line

2022-06-21 11:40 UTC, YuryShkoda commented on package-lock.json
> +    "node_modules/@types/tough-cookie": {
Why `package-lock.json` has been changed without changes to `package.json`?

2022-06-21 12:34 UTC, merged